### ISSUE TITLE
Do the groovy scripts overwrite created projects?

### ISSUE THREAD

**Issue by enriquegh** [enriquegh/jenkins-in-the-box#1]
*Summary*
If you use the -v option on Docker you can mount a Volume into Docker to use your own JENKINS_HOME folder.
This looks something like:

docker run -p 8080:8080 -p 50000:50000 -v /Users/enriquegonzalez/dockerfiles/jenkins_home_lts:/var/jenkins_home support_jenkins
Based on the way our groovy scripts are handled, they get executed after Jenkins is started.
This means that any projects already living in jenkins_home will already be loaded.

*Questions*
- Do groovy scripts overwrite already created projects?
- If they don't, is there a way to force them to?

**Comment by enriquegh** [comment]
They do not. If a project already exists, the groovy script will fail.
Should probably catch the exception:

```
WARNING: Failed to run script file:/var/jenkins_home/init.groovy.d/createFreestyleProject.groovy
java.lang.IllegalArgumentException: already an item 'sample-java-freestyle'
	at jenkins.model.Jenkins.add(Jenkins.java:2930)
	at jenkins.model.DirectlyModifiableTopLevelItemGroup$add.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at createFreestyleProject.run(createFreestyleProject.groovy:42)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by enriquegh** [comment]
There is a way to try and delete the project and then add it again:
https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#putItem-hudson.model.TopLevelItem-

Would be nice to have a way to have the user choose this behavior.
